"""Generate the reviewable view of the 124 opportunity_signal nuggets: grouped by
opportunity_topic, one subsection per signal type (A/B/C) within each topic.
Regenerate this any time tag_nuggets.py or tag_opportunity_topics.py re-runs.

signal_strength (A/B/C) is a type, not a rank -- three different kinds of value a
nugget can carry, not best-to-worst. Sorted A-then-B-then-C purely for a consistent
read order, same as the topic list is sorted by count.

Rubric: reference/opportunity-topic-taxonomy-v1.md.
"""
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
GOLD_DIR = ROOT / "data" / "gold"
SILVER_INTERVIEWS = ROOT / "data" / "silver" / "interviews.jsonl"
OUT_PATH = ROOT / "data" / "opportunity_review.md"

TOPIC_LABELS = {
    "customer-discovery": "Customer Discovery & Demand Validation",
    "product-mvp": "Product & MVP Strategy",
    "growth-marketing": "Growth, Marketing & Channels",
    "hiring-people": "Hiring & People Ops",
    "pricing-economics": "Pricing & Unit Economics",
    "ops-failure": "Ops & Failure Modes",
    "leadership-founder": "Leadership & Founder Psychology",
    "market-timing": "Market Timing & Competitive Dynamics",
}
TYPE_ORDER = {"A": 0, "B": 1, "C": 2}
TYPE_LABELS = {
    "A": "Type A -- live gap (names a specific unsolved pain point or market gap)",
    "B": "Type B -- replicable practice (a tactic/heuristic another founder could copy)",
    "C": "Type C -- color/anecdote (instructive context, not directly actionable)",
}


def load_interview_metadata():
    by_video_id = {}
    with SILVER_INTERVIEWS.open() as f:
        for line in f:
            row = json.loads(line)
            by_video_id[row["video_id"]] = row
    return by_video_id


def main():
    metadata = load_interview_metadata()
    by_topic = {topic: [] for topic in TOPIC_LABELS}
    interviewees = {}

    for path in sorted(GOLD_DIR.glob("*.json")):
        data = json.loads(path.read_text())
        video_id = path.stem
        meta = metadata.get(video_id, {})
        name = data["interviewee_name"]
        interviewees[name] = {
            "title": meta.get("interviewee_title", data.get("interviewee_title", "")),
            "bio": meta.get("interviewee_bio", ""),
            "interview_date": (meta.get("published_at") or "")[:10],
            "youtube_url": meta.get("youtube_url", ""),
        }
        for nugget in data["nuggets"]:
            if not nugget.get("opportunity_signal"):
                continue
            by_topic[nugget["opportunity_topic"]].append(
                {
                    "interviewee": name,
                    "type": nugget["signal_strength"],
                    "summary": nugget["summary"],
                    "quote": nugget.get("quote", ""),
                }
            )

    lines = [
        "# Opportunity-Signal Review", "",
        "Generated by `scripts/generate_opportunity_review.py`. Grouped by topic, "
        "then by signal type (A/B/C -- a kind of value, not a quality rank). "
        "Rubric: `reference/opportunity-topic-taxonomy-v1.md`.", "",
    ]

    total = sum(len(v) for v in by_topic.values())
    lines.append(f"**{total} nuggets total, across {len(interviewees)} interviewees.**")
    lines.append("")

    lines.append("## Interviewees")
    lines.append("")
    lines.append("| Name | Title | Interview date | Video |")
    lines.append("|---|---|---|---|")
    for name in sorted(interviewees):
        info = interviewees[name]
        video_link = f"[link]({info['youtube_url']})" if info["youtube_url"] else ""
        lines.append(
            f"| {name} | {info['title']} | {info['interview_date']} | {video_link} |"
        )
    lines.append("")

    lines.append("## Topic counts")
    lines.append("")
    for topic, items in sorted(by_topic.items(), key=lambda kv: -len(kv[1])):
        types = {"A": 0, "B": 0, "C": 0}
        for item in items:
            types[item["type"]] += 1
        lines.append(
            f"- {TOPIC_LABELS[topic]}: {len(items)} "
            f"(A={types['A']}, B={types['B']}, C={types['C']})"
        )
    lines.append("")

    for topic, items in sorted(by_topic.items(), key=lambda kv: -len(kv[1])):
        if not items:
            continue
        lines.append(f"## {TOPIC_LABELS[topic]}")
        lines.append("")
        items.sort(key=lambda x: TYPE_ORDER[x["type"]])
        for item in items:
            info = interviewees[item["interviewee"]]
            byline = f"{item['interviewee']}, {info['title']}" if info["title"] else item["interviewee"]
            if info["interview_date"]:
                byline += f" (interviewed {info['interview_date']})"
            lines.append(f"### [{TYPE_LABELS[item['type']]}] {byline}")
            lines.append("")
            lines.append(item["summary"])
            lines.append("")

    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_PATH} ({total} nuggets, {len(interviewees)} interviewees)")


if __name__ == "__main__":
    main()
